language: python
python:
  - "2.7"
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - pip install coveralls
  - sudo apt-get install python-matplotlib python-numpy python-scipy python-sklearn
  - pip install -r requirements/ai.txt
script:
  - "./scripts/test.sh"
  - "./scripts/i18n.sh"
  - "python setup.py install"
after_success:
  coveralls
